### ISSUE TITLE
Can you provide the weight of the model? Thank you!!!!

### ISSUE THREAD

**Issue by GaozhengPei** [ml-postech/robust-evaluation-of-diffusion-based-purification#3]
"For SVHN, the [DDPM architecture](https://arxiv.org/abs/2006.11239) is adapted, and we have trained the model accordingly."
"For SVHN, we have trained a WideResNet-28-10, available from [this source](https://github.com/szagoruyko/wide-residual-networks)."
Can you provide the weight of SVHNDiffusion and also the weight of WideResNet-28-10 for SVHN. We really need them. 
Thank you very much!!!

**Comment by Minjong-Lee** [comment]
I'm sorry, but it seems difficult to share the trained model right away. I had stored the model on our server, but it seems that I lost it when the server was formatted. Although I have kept the related files separately, it seems that the SVHN model is missing from those files. (I think I should double-check this.) I should have managed it more carefully, but I was careless. I sincerely apologize for that. I can retrain the model and re-release the code, but it will take some time to do so. I'm really sorry for this.
